# Generated by Django 5.1.6 on 2025-03-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='filename',
        ),
    ]
